utilitycss/utility

package.json, src/modules/index.js, src/modules/opacity.js, src/modules/outline.js, src/modules/transform.js, src/modules/transition.js
=> add opacity, outline, transform, transition

package.json, src/modules/series.js, src/util/applyRules.js, src/util/defineClass.js, src/util/defineSeries.js, utility.config.default.js
=> add support for pseudoclasses

package.json, src/util/applyRules.js, yarn.lock
=> fix pseudoClasses

package.json, src/util/defineSeries.js
=> fix: remove unused separators

package.json, src/util/applyRules.js
=> Fix pseudo for single values

example/example.config.js, package.json, src/modules/index.js, src/modules/white-space.js, src/util/applyRules.js
@sylvesteraswin 
- support responsiveWhiteList and responsiveBlackList
- add white-space module
=> feat: responsive white and black list

package.json, src/modules/background-image.js
=> fix: Background image key value

package.json, src/helpers/save-file.js, src/util/defineClass.js
@sylvesteraswin 
- allow unescaped `_` in class names
=> fix: class escaping

package.json, yarn.lock
=> chore: update package vulnerabilities

.travis.yml, package.json
=> fix: add skip cleanup

.travis.yml, package.json
=> fix: adding travis edge

example/example.config.js, package.json, src/plugins/docs.js, src/plugins/index.js, src/plugins/json.js, src/util/index.js, src/util/traverse.js
@sylvesteraswin 
add json plugin, that output a json object with modules as keys containing an array of css rules.
meta fields are propagated.
=> feat: add json plugin

package.json, src/plugins/json.js
=> fix: return root in json plugin

example/example.config.js, package.json, src/index.ts, src/modules/box-shadow.js, src/modules/index.js, src/util/computeStyles.ts
1. Add `box-shadow` module with `none` and `values` support.
1. Add module in `index`.
1. Add examples.
=> feat: support box-shadow

package.json, src/modules/animation.js, src/modules/letter-spacing.js, src/modules/line-height.js, src/modules/pointer-events.js
Add support for
1. animation
1. letter-spacing
1. line-height
1. pointer-events
@axyz
=> feat: add support for more utilities

package.json, src/modules/index.js, src/modules/user-select.js
1. Adding missing imports.
1. Add support for `user-select`.
@axyz
=> fix: missed imports

package.json, src/modules/pointer-events.js
=> fix: meta name for pointer-events

example/example.config.js, package.json, src/util/responsive.js
Close: https://github.com/utilitycss/utility/issues/37
as per issue, but always put the breakpoint last 
e.g. 
```css
@media screen and (min-width: 48rem) {
.borderNone_ns {
border: none
}
.borderNone_hover_ns:hover {
border: none
}
}
```
=> fix: responsive pseudoclasses

package.json, src/helpers/build-sections.ts, src/index.ts
=> fix: remove console log

package.json
=> fix: cli bin path

__tests__/all-defaults-with-json/transform.test.ts, __tests__/custom-config/config.ts, __tests__/custom-config/fixtures/expected-modules.json, __tests__/custom-config/fixtures/expected.css, __tests__/custom-config/transform.test.ts, __tests__/custom-inline-config/config.ts, example/example.config.js, example/example.css, package.json, src/util/defineClass.ts, src/util/responsive.ts, src/util/template.ts
@sylvesteraswin 
- support for :global(...) patterns in nested rules templates
=> feat: support :global() templates

package.json, src/modules/index.ts, src/modules/word-break.ts
@axyz 
1. Add `word-break` module.
=> feat: add word-break module

.travis.yml, package.json, src/modules/list-style.ts
1. Add `list-style-type`
2. Add `list-style-position`
=> feat: add list-style position and type

.travis.yml, package.json
=> fix: Node 14

package.json, yarn.lock
=> fix: downgrade postcss
